### PR TITLE
updated readme

### LINKED ISSUE #30: Better description of library in README
Can we have a more specific description of what this library does?

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #30

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@kgerheiser or @GeorgeVandenberghe-NOAA please review so I can merge...

**Comment by GeorgeVandenberghe-NOAA** [comment]
The documentation is a huge improvement on what was available before.   This looks good.   This build doesn't actually require cmake/3.15 but others  do and for consistency I concur it's okay to require it for all of NCEPLIBS.   I thought about adding sunset dates for spectral model stuff and it's API in other NCEP codes but decided, management could just change these and the documentation would then silently become incorrect so.. not added.  Better as is.

**Review by GeorgeVandenberghe-NOAA — APPROVED** [review]
Commented in the PR on thoughts. It's best as is without any further changes of mine, so yes, merge.

**Comment by edwardhartnett** [comment]
@GeorgeVandenberghe-NOAA in terms of CMake files, all I did was correct the comments at the top of the file. I didn't mess with the required CMake version. ;-)

I'm glad you approve of the documentation - more is needed! ;-) But I agree that overall there has been a lot of good progress.

**Pull request merged**
